<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/04 17:50:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=xuanduong_jobeet',
  'username' => 'root',
  'password' => '1',
  'name' => 'doctrine',
)),);
