<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/05 13:53:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=xuanduong_jobeet_test',
  'username' => 'root',
  'password' => '1',
  'name' => 'doctrine',
)),);
