<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/01 21:40:18

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=xuanduong_jobeet',
  'username' => 'root',
  'password' => '1',
  'name' => 'doctrine',
)),);
