<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/09/14 05:07:12
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 5,
));
