<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/17 00:49:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=xuanduong_jobeet;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
